# -*- coding: utf-8 -*-
"""hw10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxAofD3QG0CjctfV8B2GVX8JFD-rAc2-
"""

def input_scores():
    scores = load_scores('score.bin')
    if scores:
        display_scores(scores)
    else:
        print("[점수 입력]")
        index = 1
        while True:
            try:
                score = int(input(f" {index}? "))
                if score == -1:
                    break
                scores.append(score)
                index += 1
            except ValueError:
                print("유효한 점수를 입력하세요.")

