# -*- coding: utf-8 -*-
"""hw6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XN-PNR6mj3HqRH-8yQQw24rOoHZzgefX
"""

def gugu():
    for i in range(1, 10):
        for j in range(2, 6):
            print(f"{j} x {i} = {j*i}\t", end="")
            if j == 5:
                print()
    print()

    for i in range(1, 10):
        for j in range(6, 10):
            print(f"{j} x {i} = {j*i}\t", end="")
        print()

gugu()

