# -*- coding: utf-8 -*-
"""hw.8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rz3el6fTFA0XFWIYGvlqbrLzQHcMvqF4
"""

shopping_bag = {}
while True:
    print('[구입]')
    pro = input('상품명? ')
    if not pro:
        break
    num = int(input('수량은? '))
    shopping_bag[pro] = num
    print(f'장바구니에 {pro} {num}개가 담겼습니다.\n')

print(f'장바구니 보기: {shopping_bag}\n')

while True:
    print('[검색]')
    find = input('장바구니에서 확인하고자 하는 상품은?')
    if not find:
        break
    if find in shopping_bag:
        print(f'{find}는 {shopping_bag[find]}개 있습니다.\n')
    else:
        print(f'{find}은(는) 장바구니에 없습니다.\n')