# -*- coding: utf-8 -*-
"""겅부

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQRcIbeyUWQHU-3CzPgAbYcFraIL78z2
"""

def separator():
  print('---------------')

def say_hello():
  separator()
  print('안녕하세요')
  print('*********')


say_hello()

def make_message(name):
  print('시작')
  print(f'반가워요 {name}\n 마침')

name= input('당신의 이름은?')
make_message(name)

def make_message(n):
  msg = '반가워요' + n
  return msg


name = input('당신의 이름은?')
make_message(name)

def show_circle_area_1():
  area = 1*1* 3.14
  print(area)

def show_circle_area_10():
  area = 10 * 10 * 3.14
  print(area)

show_circle_area_1()
show_circle_area_10()

def show_circle_area(r):
  area = r*r*3.14
  print(area)

show_circle_area(1)
show_circle_area(10)

def get_circle_area(r):
  area = r*r*3.14
  return area

res1 = get_circle_area(1)
res2 = get_circle_area(10)
res1
res2

def get_radius(prompt):
  r= int(input(prompt))
  return r

def get_circle_area(r):
  area = r * r * 3.14
  return area


radius = get_radius('넓이를 구하고자 하는 원의 반지름은?')
a = get_circle_area(radius)
print(f'반지름 {radius}인 원의 넓이: 3.14*{radius}*{radius} = {a}')

def get_radius(prompt):
    r = int(input(prompt))
    return r
print('넓이를 구하고자 하는 원의 반지름은?')
prompt = int(input())
print('반지름' , prompt , '인 원의 넓이',
      '=', '3.14 *' ,prompt,'*' ,prompt ,'=' , prompt * prompt * 3.14 )

# 반지름구하기

def get_n(prompt1, prompt2):
  n1= int(input(prompt1))
  n2 = int(input(prompt2))
  return [n1, n2]


def show_division(n1,n2):
  answer = n1 // n2
  rest = n1 % n2
  return [answer, rest]


num = get_n('피젯수를 입력하세요', '젯수를 입력하세요')

ans = show_division(num[0], num[1])

print(f'몫 = {ans[0]}\n나머지 = {ans[1]}')

# 반지름 구하기2

def show_division(n1,n2):
  ans = n1//n2
  rest = n1&n2
  print(f'몫={ans}\n나머지={rest}')

num1 = int(input('정수'))
num2 = int(input('정수2'))

show_division(num1,num2)

# 잔돈 계산하기

def show_change(money):
  print(f'잔돈: {money}원')
  m5000 = money // 5000
  rest = money % 5000
  m1000 = rest // 1000
  print(f'5000원권 {m5000}장\n1000원권 {m1000}장')

total_cost = int(input('구매받은 물건의 총구매 금액은?'))
payment = int(input('고객으로부터 지불받은 금액은?'))
cost = payment - total_cost
show_change(cost)

# 화씨온도 > 섭씨온도

def get_f(prompt):
  prompt =int(input(prompt))
  return prompt

def fahrenheit_to_celsius(f):
  c = 5/9*(f-32)
  return c


f = get_f('변환하고자 하는 화씨온도는?')
c = fahrenheit_to_celsius(f)

print(f'화씨 {f}도는 섭씨 {c}도')

# 3주차 4.7

def exchange(m):
  a = m // 500
  rest = m%500
  b = rest // 100
  rest = rest % 100
  c = rest // 50
  rest = rest % 50
  d = rest // 10
  rest = rest % 10
  print(a, b, c, d)


a = int(input('돈'))
exchange(a)

# 3주차 4.3 시 분 초 변환하기

def convert_time(t):
  h= t // 3600
  rest = t % 3600
  m = rest // 60
  rest = rest% 60
  print(h,m,rest)

t =int(input('초?'))
convert_time(t)

# 4주차 5.5 할인율 계산하기

def get_fixed_price(discount_rate, discount_price) :
    price = discount_price / (1 - discount_rate / 100)
    return price

discount_rate = int(input('할인율은?'))
a_discount_price = int(input('a 상품의 할인된 가격은?'))
b_discount_price = int(input('b 상품의 할인된 가격은?'))

a_price = get_fixed_price(discount_rate, a_discount_price)
b_price = get_fixed_price(discount_rate, b_discount_price)
print('A 상품의 정가는 ', a_price, '원')
print('B 상품의 정가는', b_price, '원')

# 5주차 실습예제

def name(prompt):
  a=input(prompt)
  print('-'*10)
  print('성:' ,a[0])
  print('이름:',a[1:])
  print('-'*10)
name('이름?')

# 5주차 6.2

def introduce(n,g):
  print(f'{n[1:]}은(는) 내년에 {g+1}학년입니다')

n = input('이름?')
g = int(input('학년?'))

introduce(n,g)

# 5주차 연습 6.5

def draw_line_string(prompt):
  a=input(prompt)
  print('-' * len(prompt)*2)
  print(a)
  print('-' * len(prompt)*2)

draw_line_string('쓰라')

# 6주차 실습예제 윤년판별하기
def year_find(year):
  if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    return True
  else :
    return False

y = int(input('연도?'))
if year_find(y) ==True :
   print(f'{y} 는윤년입니다.')
else : print(f'{y} 는 평년입니다')

# 6주차 연습 7.2
def year_find(year):
  if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    return True
  else :
    return False

def month_days(year, m):
  if (year == True):
    if m == 2 :
      return 28
    elif m in [1,3,5,7,8,10,12]:
      return 31
    else: return 30
  else:
    if m== 2:
      return 29
    elif m in [1,3,5,7,8,10 ,12]:
      return 31
    else: return 30

year= int(input('dㅕㄴ도'))
m = int(input('월'))

year_find(year)
month_days(year,m)

print(f'{year}년 {m}월은 {month_days(year,m)}까지잇슴')

# 6주차 연습 7.4

def input_age(prompt):
  a=int(input(prompt))
  if a >= 0 and a <= 120:
    return a
  else : return -1


def is_adult(a):
  if a >= 19:
    return True
  else : return False



age = input_age('나이')

if age >=0:
  if is_adult(age) == True:
    print('성인')
  else: print('성ㅇ인아님')

else :print('자라')

# while 연습문제 8.1



def gugu():
    for i in range(1, 10):
        for j in range(2, 6):
            print(f"{j} x {i} = {j*i}\t", end="")
            if j == 5:
                print()
    print()

    for i in range(1, 10):
        for j in range(6, 10):
            print(f"{j} x {i} = {j*i}\t", end="")
        print()

gugu()
#구구단만들ㄷ기























def gugu():
    for i in range(1, 10):
        for j in range(2, 6):
            print(f"{j} x {i} = {j*i}\t", end="")
            if j == 5:
                print()
    print()

    for i in range(1, 10):
        for j in range(6, 10):
            print(f"{j} x {i} = {j*i}\t", end="")
        print()

gugu()
#구구단만들ㄷ기

